env: "local" # Возможные значения: local, dev, prod

postgresql:
  host: "db"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "messages"
  sslmode: "disable"

kafka:
  brokers:
    - "kafka:9092"
  topic: "messages"

http:
  port: 8080
  timeout: 4s
  iddle_timeout: 60s

storage_path: "./storage/messageSrv.db"
